Introduce output schemas
qir-alliance/qir-spec pull request #36
Opened 2023-10-25 07:19 UTC by cesarzc

This change introduces two output schemas for QIR, ordered and labeled.

2023-10-25 07:37 UTC, cesarzc commented
I have read the Contributor License Agreement and I hereby accept the Terms.

2023-10-25 07:37 UTC, cesarzc commented
recheck

2025-05-21 13:04 UTC, qartik requested changes
I believe the examples for labeled schema all have the incorrect schema name.

2025-05-21 13:04 UTC, qartik commented on specification/under_development/output_schemas/Labeled.md
> +HEADER\tschema_name\tordered
```suggestion
HEADER\tschema_name\tlabeled
```

2025-05-21 13:04 UTC, qartik commented on specification/under_development/output_schemas/Labeled.md
> +HEADER\tschema_name\tordered
```suggestion
HEADER\tschema_name\tlabeled
```

2025-05-21 13:04 UTC, qartik commented on specification/under_development/output_schemas/Labeled.md
> +HEADER\tschema_name\tordered
```suggestion
HEADER\tschema_name\tlabeled
```

2025-05-21 13:04 UTC, qartik commented on specification/under_development/output_schemas/Labeled.md
> +HEADER\tschema_name\tordered
```suggestion
HEADER\tschema_name\tlabeled
```

2025-05-21 13:04 UTC, qartik commented on specification/under_development/output_schemas/Labeled.md
> +HEADER\tschema_name\tordered
```suggestion
HEADER\tschema_name\tlabeled
```

2025-06-17 13:23 UTC, qartik commented
I have a PR that forks from this one and adds corrections at https://github.com/qir-alliance/qir-spec/pull/50

2025-08-27 15:32 UTC, bettinaheim commented
superceded by https://github.com/qir-alliance/qir-spec/pull/50

2025-08-27 15:32 UTC, closed without merging